// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Data;

#nullable disable

namespace WebStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260109225523_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebStore.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2028, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1707),
                            ImageName = "laptop.jpg",
                            Name = "Laptop Gamingowy",
                            Price = 4500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2029, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1754),
                            ImageName = "mysz.jpg",
                            Name = "Mysz Bezprzewodowa",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2031, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1757),
                            ImageName = "monitor.jpg",
                            Name = "Monitor 24 cale",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2036, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1759),
                            ImageName = "hdmi.jpg",
                            Name = "Kabel HDMI",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 1, 16, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1762),
                            ImageName = "mleko.jpg",
                            Name = "Mleko 3.2%",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 1, 12, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1771),
                            ImageName = "chleb.jpg",
                            Name = "Chleb Pełnoziarnisty",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2027, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1773),
                            ImageName = "kawa.jpg",
                            Name = "Kawa Ziarnista 1kg",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1776),
                            ImageName = "czekolada.jpg",
                            Name = "Czekolada Mleczna",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2027, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1779),
                            ImageName = "koszulka.jpg",
                            Name = "Koszulka T-Shirt",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2028, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1782),
                            ImageName = "jeansy.jpg",
                            Name = "Jeansy Męskie",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2029, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1785),
                            ImageName = "kurtka.jpg",
                            Name = "Kurtka Zimowa",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2031, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1787),
                            ImageName = "czapka.jpg",
                            Name = "Czapka z daszkiem",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1790),
                            ImageName = "plyn_naczynia.jpg",
                            Name = "Płyn do naczyń",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2027, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1793),
                            ImageName = "proszek_pranie.jpg",
                            Name = "Proszek do prania",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1795),
                            ImageName = "mydlo.jpg",
                            Name = "Mydło w płynie",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2031, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1798),
                            ImageName = "dlugopisy.jpg",
                            Name = "Zestaw długopisów",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2036, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1800),
                            ImageName = "notatnik.jpg",
                            Name = "Notatnik A4",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2030, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1803),
                            ImageName = "parasol.jpg",
                            Name = "Parasol",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2027, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1880),
                            Name = "Towar Testowy nr 19",
                            Price = 20.723321629681m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2027, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1884),
                            Name = "Towar Testowy nr 20",
                            Price = 11.9709161831033m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2027, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1895),
                            Name = "Towar Testowy nr 21",
                            Price = 54.7134516764868m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2027, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1899),
                            Name = "Towar Testowy nr 22",
                            Price = 29.710633844048m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2027, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1903),
                            Name = "Towar Testowy nr 23",
                            Price = 33.0366726604742m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2028, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1907),
                            Name = "Towar Testowy nr 24",
                            Price = 46.7027962802722m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2028, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1913),
                            Name = "Towar Testowy nr 25",
                            Price = 85.7844463537093m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2028, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1917),
                            Name = "Towar Testowy nr 26",
                            Price = 85.5350900960518m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2028, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1920),
                            Name = "Towar Testowy nr 27",
                            Price = 99.2003011059704m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1924),
                            Name = "Towar Testowy nr 28",
                            Price = 63.7963642320789m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2028, 6, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1929),
                            Name = "Towar Testowy nr 29",
                            Price = 43.7076053168998m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2028, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1932),
                            Name = "Towar Testowy nr 30",
                            Price = 41.0154788628892m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2028, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1936),
                            Name = "Towar Testowy nr 31",
                            Price = 45.1953781986328m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2028, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1939),
                            Name = "Towar Testowy nr 32",
                            Price = 65.7440913003222m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1945),
                            Name = "Towar Testowy nr 33",
                            Price = 26.9443617203983m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2028, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1950),
                            Name = "Towar Testowy nr 34",
                            Price = 43.5850088345587m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2028, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1954),
                            Name = "Towar Testowy nr 35",
                            Price = 31.6123866277649m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2029, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1957),
                            Name = "Towar Testowy nr 36",
                            Price = 46.3792191329492m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2029, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1963),
                            Name = "Towar Testowy nr 37",
                            Price = 72.9894098715166m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2029, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1966),
                            Name = "Towar Testowy nr 38",
                            Price = 39.4024450477197m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2029, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1970),
                            Name = "Towar Testowy nr 39",
                            Price = 44.9792045939076m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2029, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(1973),
                            Name = "Towar Testowy nr 40",
                            Price = 78.1800942787078m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2029, 6, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2042),
                            Name = "Towar Testowy nr 41",
                            Price = 91.2486661532264m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2029, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2048),
                            Name = "Towar Testowy nr 42",
                            Price = 36.0033799899872m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2029, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2051),
                            Name = "Towar Testowy nr 43",
                            Price = 58.9933778599974m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2029, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2055),
                            Name = "Towar Testowy nr 44",
                            Price = 38.3331796130647m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2029, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2061),
                            Name = "Towar Testowy nr 45",
                            Price = 96.2303072303264m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2029, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2064),
                            Name = "Towar Testowy nr 46",
                            Price = 54.6434516202231m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2029, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2068),
                            Name = "Towar Testowy nr 47",
                            Price = 87.0685483478416m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2030, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2071),
                            Name = "Towar Testowy nr 48",
                            Price = 43.2615421031639m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2030, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2077),
                            Name = "Towar Testowy nr 49",
                            Price = 63.7536367454758m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2030, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2080),
                            Name = "Towar Testowy nr 50",
                            Price = 106.910075210218m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2030, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2083),
                            Name = "Towar Testowy nr 51",
                            Price = 103.402609804063m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2030, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2087),
                            Name = "Towar Testowy nr 52",
                            Price = 57.9550628700516m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2030, 6, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2092),
                            Name = "Towar Testowy nr 53",
                            Price = 89.1432228282673m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2030, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2096),
                            Name = "Towar Testowy nr 54",
                            Price = 27.5923807630396m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2030, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2099),
                            Name = "Towar Testowy nr 55",
                            Price = 10.3155852306541m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2030, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2103),
                            Name = "Towar Testowy nr 56",
                            Price = 34.4710910471286m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2030, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2108),
                            Name = "Towar Testowy nr 57",
                            Price = 82.7399933908135m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2030, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2112),
                            Name = "Towar Testowy nr 58",
                            Price = 89.7783915545923m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2030, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2115),
                            Name = "Towar Testowy nr 59",
                            Price = 102.853564832415m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2031, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2119),
                            Name = "Towar Testowy nr 60",
                            Price = 87.5752133974468m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2031, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2124),
                            Name = "Towar Testowy nr 61",
                            Price = 23.2835097452838m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2031, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2128),
                            Name = "Towar Testowy nr 62",
                            Price = 24.8266754934236m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2031, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2131),
                            Name = "Towar Testowy nr 63",
                            Price = 90.7178217533794m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2031, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2135),
                            Name = "Towar Testowy nr 64",
                            Price = 105.541105863811m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2031, 6, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2140),
                            Name = "Towar Testowy nr 65",
                            Price = 71.4668618332382m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2031, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2146),
                            Name = "Towar Testowy nr 66",
                            Price = 90.1803267813444m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2031, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2149),
                            Name = "Towar Testowy nr 67",
                            Price = 21.8390835882563m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2031, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2153),
                            Name = "Towar Testowy nr 68",
                            Price = 29.9832426006689m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2031, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2158),
                            Name = "Towar Testowy nr 69",
                            Price = 83.451929798758m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2031, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2162),
                            Name = "Towar Testowy nr 70",
                            Price = 28.5010653967063m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2031, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2165),
                            Name = "Towar Testowy nr 71",
                            Price = 24.0919714407404m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2032, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2168),
                            Name = "Towar Testowy nr 72",
                            Price = 84.4327442630165m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2032, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2174),
                            Name = "Towar Testowy nr 73",
                            Price = 53.5432266979424m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2032, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2177),
                            Name = "Towar Testowy nr 74",
                            Price = 13.3827639281976m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2032, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2181),
                            Name = "Towar Testowy nr 75",
                            Price = 15.2131975374003m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2032, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2235),
                            Name = "Towar Testowy nr 76",
                            Price = 43.4910578865107m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2032, 6, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2241),
                            Name = "Towar Testowy nr 77",
                            Price = 68.1794917145062m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2032, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2244),
                            Name = "Towar Testowy nr 78",
                            Price = 78.7540496717082m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2032, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2248),
                            Name = "Towar Testowy nr 79",
                            Price = 109.543323754364m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2032, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2251),
                            Name = "Towar Testowy nr 80",
                            Price = 95.2857323946832m
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2032, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2257),
                            Name = "Towar Testowy nr 81",
                            Price = 24.5336427330319m
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2032, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2260),
                            Name = "Towar Testowy nr 82",
                            Price = 77.4757275212788m
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2032, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2264),
                            Name = "Towar Testowy nr 83",
                            Price = 15.2800884104758m
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2033, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2268),
                            Name = "Towar Testowy nr 84",
                            Price = 83.9619183698128m
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2033, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2273),
                            Name = "Towar Testowy nr 85",
                            Price = 34.1238394888885m
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2033, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2276),
                            Name = "Towar Testowy nr 86",
                            Price = 51.0893742812264m
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2033, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2280),
                            Name = "Towar Testowy nr 87",
                            Price = 16.6500537945502m
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2033, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2283),
                            Name = "Towar Testowy nr 88",
                            Price = 31.6947851161281m
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2033, 6, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2288),
                            Name = "Towar Testowy nr 89",
                            Price = 72.4018654948101m
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2033, 7, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2292),
                            Name = "Towar Testowy nr 90",
                            Price = 44.025575247861m
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2033, 8, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2295),
                            Name = "Towar Testowy nr 91",
                            Price = 101.277697018821m
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2033, 9, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2299),
                            Name = "Towar Testowy nr 92",
                            Price = 63.6486290689557m
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2033, 10, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2304),
                            Name = "Towar Testowy nr 93",
                            Price = 83.8189247558677m
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2033, 11, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2308),
                            Name = "Towar Testowy nr 94",
                            Price = 104.162512358636m
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2033, 12, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2311),
                            Name = "Towar Testowy nr 95",
                            Price = 54.8065536137609m
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2034, 1, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2314),
                            Name = "Towar Testowy nr 96",
                            Price = 84.7467861136292m
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2034, 2, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2320),
                            Name = "Towar Testowy nr 97",
                            Price = 39.0822732317024m
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2034, 3, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2323),
                            Name = "Towar Testowy nr 98",
                            Price = 44.8067012633719m
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2034, 4, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2327),
                            Name = "Towar Testowy nr 99",
                            Price = 21.378137262689m
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2034, 5, 9, 23, 55, 22, 22, DateTimeKind.Local).AddTicks(2331),
                            Name = "Towar Testowy nr 100",
                            Price = 87.2474333042759m
                        });
                });

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spożywcze"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odzież"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chemia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebStore.Models.Article", b =>
                {
                    b.HasOne("WebStore.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
