// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Data;

#nullable disable

namespace WebStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260109161723_InitialWithSeedData")]
    partial class InitialWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebStore.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2028, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6337),
                            ImageName = "laptop.jpg",
                            Name = "Laptop Gamingowy",
                            Price = 4500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2029, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6389),
                            ImageName = "mysz.jpg",
                            Name = "Mysz Bezprzewodowa",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2031, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6392),
                            ImageName = "monitor.jpg",
                            Name = "Monitor 24 cale",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2036, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6394),
                            ImageName = "hdmi.jpg",
                            Name = "Kabel HDMI",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 1, 16, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6397),
                            ImageName = "mleko.jpg",
                            Name = "Mleko 3.2%",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 1, 12, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6402),
                            ImageName = "chleb.jpg",
                            Name = "Chleb Pełnoziarnisty",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2027, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6404),
                            ImageName = "kawa.jpg",
                            Name = "Kawa Ziarnista 1kg",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 7, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6408),
                            ImageName = "czekolada.jpg",
                            Name = "Czekolada Mleczna",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2027, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6410),
                            ImageName = "koszulka.jpg",
                            Name = "Koszulka T-Shirt",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2028, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6412),
                            ImageName = "jeansy.jpg",
                            Name = "Jeansy Męskie",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2029, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6415),
                            ImageName = "kurtka.jpg",
                            Name = "Kurtka Zimowa",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2031, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6417),
                            ImageName = "czapka.jpg",
                            Name = "Czapka z daszkiem",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6420),
                            ImageName = "płyn_naczynia.jpg",
                            Name = "Płyn do naczyń",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2027, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6422),
                            ImageName = "proszek_pranie.jpg",
                            Name = "Proszek do prania",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6424),
                            ImageName = "mydlo.jpg",
                            Name = "Mydło w płynie",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2031, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6479),
                            ImageName = "dlugopisy.jpg",
                            Name = "Zestaw długopisów",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2036, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6482),
                            ImageName = "notatnik.jpg",
                            Name = "Notatnik A4",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2030, 1, 9, 17, 17, 23, 375, DateTimeKind.Local).AddTicks(6484),
                            ImageName = "parasol.jpg",
                            Name = "Parasol",
                            Price = 35.00m
                        });
                });

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spożywcze"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odzież"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chemia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("WebStore.Models.Article", b =>
                {
                    b.HasOne("WebStore.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
