// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Data;

#nullable disable

namespace WebStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260109201648_AddIdentitySchema")]
    partial class AddIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebStore.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2028, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9326),
                            ImageName = "laptop.jpg",
                            Name = "Laptop Gamingowy",
                            Price = 4500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2029, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9377),
                            ImageName = "mysz.jpg",
                            Name = "Mysz Bezprzewodowa",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2031, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9380),
                            ImageName = "monitor.jpg",
                            Name = "Monitor 24 cale",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ExpirationDate = new DateTime(2036, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9382),
                            ImageName = "hdmi.jpg",
                            Name = "Kabel HDMI",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 1, 16, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9385),
                            ImageName = "mleko.jpg",
                            Name = "Mleko 3.2%",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 1, 12, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9388),
                            ImageName = "chleb.jpg",
                            Name = "Chleb Pełnoziarnisty",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2027, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9391),
                            ImageName = "kawa.jpg",
                            Name = "Kawa Ziarnista 1kg",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ExpirationDate = new DateTime(2026, 7, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9393),
                            ImageName = "czekolada.jpg",
                            Name = "Czekolada Mleczna",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2027, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9396),
                            ImageName = "koszulka.jpg",
                            Name = "Koszulka T-Shirt",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2028, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9398),
                            ImageName = "jeansy.jpg",
                            Name = "Jeansy Męskie",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2029, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9401),
                            ImageName = "kurtka.jpg",
                            Name = "Kurtka Zimowa",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            ExpirationDate = new DateTime(2031, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9404),
                            ImageName = "czapka.jpg",
                            Name = "Czapka z daszkiem",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9406),
                            ImageName = "płyn_naczynia.jpg",
                            Name = "Płyn do naczyń",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2027, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9408),
                            ImageName = "proszek_pranie.jpg",
                            Name = "Proszek do prania",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            ExpirationDate = new DateTime(2028, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9411),
                            ImageName = "mydlo.jpg",
                            Name = "Mydło w płynie",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2031, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9414),
                            ImageName = "dlugopisy.jpg",
                            Name = "Zestaw długopisów",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2036, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9416),
                            ImageName = "notatnik.jpg",
                            Name = "Notatnik A4",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            ExpirationDate = new DateTime(2030, 1, 9, 21, 16, 48, 25, DateTimeKind.Local).AddTicks(9418),
                            ImageName = "parasol.jpg",
                            Name = "Parasol",
                            Price = 35.00m
                        });
                });

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronika"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spożywcze"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Odzież"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chemia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebStore.Models.Article", b =>
                {
                    b.HasOne("WebStore.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
