name=ButtonHandler
version=1.0.0
author=Jakub Kacprzyk
maintainer=Jakub Kacprzyk
sentence=Library for button handling (short & long press) using interrupts
paragraph=Supports debouncing, short/long press callbacks, uses pin-change interrupts on AVR
category=Input
architectures=*
